name: Test Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test imports
      run: |
        python -c "
        try:
            import sys
            sys.path.append('.')
            from ui.main_window import MainWindow
            from utils.file_detector import FileDetector
            from utils.conversion_manager import ConversionManager
            from utils.history_manager import HistoryManager
            print('[SUCCESS] All imports successful')
        except Exception as e:
            print(f'[ERROR] Import failed: {e}')
            exit(1)
        "

    - name: Test file detection
      run: |
        python -c "
        from utils.file_detector import FileDetector
        detector = FileDetector()

        # Test file type detection
        assert detector.get_file_type('test.jpg') == 'image'
        assert detector.get_file_type('test.pdf') == 'document'
        assert detector.get_file_type('test.mp3') == 'audio'
        assert detector.get_file_type('test.mp4') == 'video'

        print('[SUCCESS] File detection tests passed')
        "

    - name: Syntax check all Python files
      run: |
        python -m py_compile main.py
        python -m py_compile ui/main_window.py
        python -m py_compile ui/advanced_settings.py
        python -m py_compile utils/file_detector.py
        python -m py_compile utils/conversion_manager.py
        python -m py_compile utils/history_manager.py
        python -m py_compile converters/base_converter.py
        python -m py_compile converters/image_converter.py
        python -m py_compile converters/document_converter.py
        python -m py_compile converters/audio_converter.py
        python -m py_compile converters/video_converter.py
        python -m py_compile converters/archive_converter.py
        python -m py_compile converters/code_converter.py
        echo "[SUCCESS] All Python files compiled successfully"